version: "3"

services:
  web:
    image: tomsik68/xampp:8
    container_name: meu-xampp-container
    ports:
      - "41061:22"
      - "41062:80"
    volumes:
      - ~/html:/opt/lampp/htdocs
      # Mapeia a pasta html do host para o xampp no container.

      - ~/my_apache_conf:/opt/lampp/apache2/conf.d
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
